### ISSUE TITLE
String changes for correct translations

### ISSUE THREAD

**Issue by mikeNG** [cyngn/android_packages_apps_CyanogenAccount-resources#1]
cmaccount_allow_access: should be "%1$s would like access to %2$s" for Japanese translation
cmaccount_tos_iagree & cmaccount_tos_link: should be integrated for Japanese translation

**Comment by scorpiodawg** [comment]
cmaccount_tos_iagree & cmaccount_tos_link are no longer used so I'll delete them. Will fix cmaccount_allow_access.
